version: '3.9'

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: postgres_d_compose
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass_key
      POSTGRES_DB: my_db
    ports:
      - "5432:5432"
    volumes: 
      - db:/var/lib/postgresql/data
      - ./postgres/migrations:/docker-entrypoint-initdb.d

  python_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./datasets:/data
    container_name: cbs_data_extractor
    depends_on: 
      - postgres    
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=pass_key
      - DB_NAME=my_db
    command: ["python", "main.py"]

volumes:
  db:
    driver: local